openapi: "3.0.0"

info:
  version: 1.0.0
  title: campus-laundry
  description: campus-laundry description


servers:
  - url: /campus-laundry


paths:
   /health:
      get:
        summary: Health Check of the services
        operationId: api.health.get
        responses:
          200:
            description: Status message from server describing current health
   /cl_get_all_employees:
      get:
        summary: GET Service to fetch data of employees
        tags:
          - cl_get_user_login
        description: |
          ## get all employee's details
          ---
          ### parameters

        operationId: api.cl_get_all_employees.get
        responses:
          '200':
            description: get user details
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/cl_get_all_employees_result'
          'default':
            description: unexpected error


components:
  schemas:
    cl_get_all_employees_result:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/cl_get_all_employees_response_results'
    cl_get_all_employees_response_results:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
